-- =====================================================
-- 资产数据批量插入
-- 包含: 股票100个、ETF 100个、期货100个、虚拟币10个
-- 总计: 310条记录
-- =====================================================

-- -----------------------------------------------------
-- 1. 股票 (Stocks) - 100个
-- -----------------------------------------------------
INSERT INTO assets (symbol, name, asset_type, market, currency, sector, exchange, is_active) VALUES
                                                                                                 ('AAPL', 'Apple Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('MSFT', 'Microsoft Corporation', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('AMZN', 'Amazon.com Inc', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NASDAQ', TRUE),
                                                                                                 ('GOOGL', 'Alphabet Inc Class A', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('META', 'Meta Platforms Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('TSLA', 'Tesla Inc', 'STOCK', 'US', 'USD', 'Automotive', 'NASDAQ', TRUE),
                                                                                                 ('NVDA', 'NVIDIA Corporation', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('JNJ', 'Johnson & Johnson', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('V', 'Visa Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('WMT', 'Walmart Inc', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NYSE', TRUE),
                                                                                                 ('JPM', 'JPMorgan Chase & Co', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('PG', 'Procter & Gamble Co', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NYSE', TRUE),
                                                                                                 ('UNH', 'UnitedHealth Group Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('HD', 'Home Depot Inc', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('DIS', 'Walt Disney Co', 'STOCK', 'US', 'USD', 'Communication Services', 'NYSE', TRUE),
                                                                                                 ('NFLX', 'Netflix Inc', 'STOCK', 'US', 'USD', 'Communication Services', 'NASDAQ', TRUE),
                                                                                                 ('ADBE', 'Adobe Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('CRM', 'Salesforce Inc', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('PEP', 'PepsiCo Inc', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NASDAQ', TRUE),
                                                                                                 ('KO', 'Coca-Cola Co', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NYSE', TRUE),
                                                                                                 ('TMO', 'Thermo Fisher Scientific Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('AVGO', 'Broadcom Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('COST', 'Costco Wholesale Corp', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NASDAQ', TRUE),
                                                                                                 ('ABBV', 'AbbVie Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('MRK', 'Merck & Co Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('DHR', 'Danaher Corporation', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('ACN', 'Accenture plc', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('NKE', 'Nike Inc', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('LIN', 'Linde plc', 'STOCK', 'US', 'USD', 'Basic Materials', 'NYSE', TRUE),
                                                                                                 ('MDT', 'Medtronic plc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('DELL', 'Dell Technologies Inc', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('BA', 'Boeing Co', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('LLY', 'Eli Lilly and Co', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('NVO', 'Novo Nordisk A/S', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('RKLB', 'Rocket Lab USA Inc', 'STOCK', 'US', 'USD', 'Industrials', 'NASDAQ', TRUE),
                                                                                                 ('IONQ', 'IonQ Inc', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('CRWD', 'CrowdStrike Holdings Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('ASTS', 'AST SpaceMobile Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('PATH', 'UiPath Inc', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('VRT', 'Vertiv Holdings Co', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('IREN', 'Iris Energy Ltd', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('SERV', 'Serve Robotics Inc', 'STOCK', 'US', 'USD', 'Industrials', 'NASDAQ', TRUE),
                                                                                                 ('GRAB', 'Grab Holdings Ltd', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('BE', 'Bloom Energy Corp', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('GILD', 'Gilead Sciences Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('ABT', 'Abbott Laboratories', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('CVNA', 'Carvana Co', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('AAL', 'American Airlines Group Inc', 'STOCK', 'US', 'USD', 'Industrials', 'NASDAQ', TRUE),
                                                                                                 ('LUV', 'Southwest Airlines Co', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('CGC', 'Canopy Growth Corp', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('KKR', 'KKR & Co Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('APD', 'Air Products and Chemicals Inc', 'STOCK', 'US', 'USD', 'Basic Materials', 'NYSE', TRUE),
                                                                                                 ('A', 'Agilent Technologies Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('MDB', 'MongoDB Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('EXR', 'Extra Space Storage Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('CSGP', 'CoStar Group Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NASDAQ', TRUE),
                                                                                                 ('GRMN', 'Garmin Ltd', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('HUBB', 'Hubbell Inc', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('CORT', 'Corcept Therapeutics Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('ARES', 'Ares Management Corp', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('JEF', 'Jefferies Financial Group Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('ABG', 'Asbury Automotive Group Inc', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('LC', 'LendingClub Corp', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('AAON', 'AAON Inc', 'STOCK', 'US', 'USD', 'Industrials', 'NASDAQ', TRUE),
                                                                                                 ('ALRM', 'Alarm.com Holdings Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('AMSC', 'American Superconductor Corp', 'STOCK', 'US', 'USD', 'Industrials', 'NASDAQ', TRUE),
                                                                                                 ('ARDX', 'Ardelyx Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('ASUR', 'Asure Software Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('ATOM', 'Atomera Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('BWB', 'Bridgewater Bancshares Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('CDLX', 'Cardlytics Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('CLPR', 'Clipper Realty Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('CNDT', 'Conduent Inc', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('CPSH', 'CPS Technologies Corp', 'STOCK', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('DEA', 'Easterly Government Properties Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('DLNG', 'Dynagas LNG Partners LP', 'STOCK', 'US', 'USD', 'Energy', 'NYSE', TRUE),
                                                                                                 ('DRD', 'DRDGOLD Ltd', 'STOCK', 'US', 'USD', 'Basic Materials', 'NYSE', TRUE),
                                                                                                 ('DXC', 'DXC Technology Co', 'STOCK', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('EAF', 'GrafTech International Ltd', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('EDUC', 'Educational Development Corp', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NASDAQ', TRUE),
                                                                                                 ('ETN', 'Eaton Corporation plc', 'STOCK', 'US', 'USD', 'Industrials', 'NYSE', TRUE),
                                                                                                 ('EVFM', 'Evofem Biosciences Inc', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('FAMI', 'Farmmi Inc', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NASDAQ', TRUE),
                                                                                                 ('FG', 'F&G Annuities & Life Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NYSE', TRUE),
                                                                                                 ('FPAY', 'FlexShopper Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('FRBA', 'First Bank', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('FRD', 'Friedman Industries Inc', 'STOCK', 'US', 'USD', 'Basic Materials', 'NYSE', TRUE),
                                                                                                 ('FRPT', 'Freshpet Inc', 'STOCK', 'US', 'USD', 'Consumer Defensive', 'NASDAQ', TRUE),
                                                                                                 ('FULT', 'Fulton Financial Corp', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('GPRK', 'GeoPark Ltd', 'STOCK', 'US', 'USD', 'Energy', 'NYSE', TRUE),
                                                                                                 ('HBB', 'Hamilton Beach Brands Holding Co', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('HCM', 'HUTCHMED China Ltd', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('HGV', 'Hilton Grand Vacations Inc', 'STOCK', 'US', 'USD', 'Consumer Cyclical', 'NYSE', TRUE),
                                                                                                 ('HLNE', 'Hamilton Lane Inc', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('HRZN', 'Horizon Technology Finance Corp', 'STOCK', 'US', 'USD', 'Financial Services', 'NASDAQ', TRUE),
                                                                                                 ('IIPR', 'Innovative Industrial Properties Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('ITGR', 'Integer Holdings Corp', 'STOCK', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('KREF', 'KKR Real Estate Finance Trust Inc', 'STOCK', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('KZIA', 'Kazia Therapeutics Ltd', 'STOCK', 'US', 'USD', 'Healthcare', 'NASDAQ', TRUE),
                                                                                                 ('LAC', 'Lithium Americas Corp', 'STOCK', 'US', 'USD', 'Basic Materials', 'NYSE', TRUE),
                                                                                                 ('LAND', 'Gladstone Land Corp', 'STOCK', 'US', 'USD', 'Real Estate', 'NASDAQ', TRUE);

-- -----------------------------------------------------
-- 2. ETF (Exchange Traded Funds) - 100个
-- -----------------------------------------------------
INSERT INTO assets (symbol, name, asset_type, market, currency, sector, exchange, is_active) VALUES
                                                                                                 ('SPY', 'SPDR S&P 500 ETF Trust', 'ETF', 'US', 'USD', 'Large Cap', 'NYSE', TRUE),
                                                                                                 ('IVV', 'iShares Core S&P 500 ETF', 'ETF', 'US', 'USD', 'Large Cap', 'NYSE', TRUE),
                                                                                                 ('VOO', 'Vanguard S&P 500 ETF', 'ETF', 'US', 'USD', 'Large Cap', 'NYSE', TRUE),
                                                                                                 ('QQQ', 'Invesco QQQ Trust', 'ETF', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('SPTM', 'SPDR Portfolio S&P 1500 Composite Stock Market ETF', 'ETF', 'US', 'USD', 'Total Market', 'NYSE', TRUE),
                                                                                                 ('SPMD', 'SPDR Portfolio S&P 400 Mid Cap ETF', 'ETF', 'US', 'USD', 'Mid Cap', 'NYSE', TRUE),
                                                                                                 ('SPYM', 'SPDR Portfolio S&P 500 ETF', 'ETF', 'US', 'USD', 'Large Cap', 'NYSE', TRUE),
                                                                                                 ('SPYG', 'SPDR Portfolio S&P 500 Growth ETF', 'ETF', 'US', 'USD', 'Large Cap Growth', 'NYSE', TRUE),
                                                                                                 ('SPYD', 'SPDR Portfolio S&P 500 High Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('SPYV', 'SPDR Portfolio S&P 500 Value ETF', 'ETF', 'US', 'USD', 'Large Cap Value', 'NYSE', TRUE),
                                                                                                 ('SPSM', 'SPDR Portfolio S&P 600 Small Cap ETF', 'ETF', 'US', 'USD', 'Small Cap', 'NYSE', TRUE),
                                                                                                 ('SPDG', 'SPDR Portfolio S&P Sector Neutral Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('SPDW', 'SPDR Portfolio Developed World ex-US ETF', 'ETF', 'US', 'USD', 'International', 'NYSE', TRUE),
                                                                                                 ('SPEM', 'SPDR Portfolio Emerging Markets ETF', 'ETF', 'US', 'USD', 'Emerging Markets', 'NYSE', TRUE),
                                                                                                 ('SPEU', 'SPDR Portfolio Europe ETF', 'ETF', 'US', 'USD', 'Europe', 'NYSE', TRUE),
                                                                                                 ('SPGM', 'SPDR Portfolio MSCI Global Stock Market ETF', 'ETF', 'US', 'USD', 'Global', 'NYSE', TRUE),
                                                                                                 ('DIA', 'SPDR Dow Jones Industrial Average ETF', 'ETF', 'US', 'USD', 'Large Cap', 'NYSE', TRUE),
                                                                                                 ('QQQM', 'Invesco NASDAQ 100 ETF', 'ETF', 'US', 'USD', 'Technology', 'NASDAQ', TRUE),
                                                                                                 ('ARKK', 'ARK Innovation ETF', 'ETF', 'US', 'USD', 'Innovation', 'NYSE', TRUE),
                                                                                                 ('AIQ', 'Global X Artificial Intelligence & Technology ETF', 'ETF', 'US', 'USD', 'AI', 'NASDAQ', TRUE),
                                                                                                 ('BOTZ', 'Global X Robotics & Artificial Intelligence ETF', 'ETF', 'US', 'USD', 'Robotics', 'NASDAQ', TRUE),
                                                                                                 ('CIBR', 'First Trust NASDAQ Cybersecurity ETF', 'ETF', 'US', 'USD', 'Cybersecurity', 'NASDAQ', TRUE),
                                                                                                 ('DRIV', 'Global X Autonomous & Electric Vehicles ETF', 'ETF', 'US', 'USD', 'EV', 'NASDAQ', TRUE),
                                                                                                 ('LIT', 'Global X Lithium & Battery Tech ETF', 'ETF', 'US', 'USD', 'Battery', 'NYSE', TRUE),
                                                                                                 ('ARKG', 'ARK Genomic Revolution ETF', 'ETF', 'US', 'USD', 'Biotech', 'NYSE', TRUE),
                                                                                                 ('ITA', 'iShares US Aerospace & Defense ETF', 'ETF', 'US', 'USD', 'Aerospace', 'NYSE', TRUE),
                                                                                                 ('GDX', 'VanEck Gold Miners ETF', 'ETF', 'US', 'USD', 'Gold', 'NYSE', TRUE),
                                                                                                 ('SLV', 'iShares Silver Trust', 'ETF', 'US', 'USD', 'Silver', 'NYSE', TRUE),
                                                                                                 ('URA', 'Global X Uranium ETF', 'ETF', 'US', 'USD', 'Uranium', 'NYSE', TRUE),
                                                                                                 ('SGOV', 'iShares 0-3 Month Treasury Bond ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('LQD', 'iShares iBoxx Investment Grade Corporate Bond ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('SHY', 'iShares 1-3 Year Treasury Bond ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('EWJ', 'iShares MSCI Japan ETF', 'ETF', 'US', 'USD', 'Japan', 'NYSE', TRUE),
                                                                                                 ('INDA', 'iShares MSCI India ETF', 'ETF', 'US', 'USD', 'India', 'NYSE', TRUE),
                                                                                                 ('KWEB', 'KraneShares CSI China Internet ETF', 'ETF', 'US', 'USD', 'China', 'NYSE', TRUE),
                                                                                                 ('EWZ', 'iShares MSCI Brazil ETF', 'ETF', 'US', 'USD', 'Brazil', 'NYSE', TRUE),
                                                                                                 ('QLD', 'ProShares Ultra QQQ', 'ETF', 'US', 'USD', 'Leveraged', 'NYSE', TRUE),
                                                                                                 ('USD', 'ProShares Ultra Semiconductors', 'ETF', 'US', 'USD', 'Leveraged', 'NYSE', TRUE),
                                                                                                 ('DOG', 'ProShares Short Dow30', 'ETF', 'US', 'USD', 'Inverse', 'NYSE', TRUE),
                                                                                                 ('PSQ', 'ProShares Short QQQ', 'ETF', 'US', 'USD', 'Inverse', 'NYSE', TRUE),
                                                                                                 ('AMZA', 'InfraCap MLP ETF', 'ETF', 'US', 'USD', 'Energy', 'NYSE', TRUE),
                                                                                                 ('VRAI', 'Virtus Real Asset Income ETF', 'ETF', 'US', 'USD', 'Real Asset', 'NYSE', TRUE),
                                                                                                 ('VCLN', 'Virtus Duff & Phelps Clean Energy ETF', 'ETF', 'US', 'USD', 'Clean Energy', 'NYSE', TRUE),
                                                                                                 ('ASGM', 'Virtus AlphaSimplex Global Macro ETF', 'ETF', 'US', 'USD', 'Global Macro', 'NYSE', TRUE),
                                                                                                 ('ASMF', 'Virtus AlphaSimplex Managed Futures ETF', 'ETF', 'US', 'USD', 'Managed Futures', 'NYSE', TRUE),
                                                                                                 ('BBC', 'Virtus Biotech Clinical Trials ETF', 'ETF', 'US', 'USD', 'Biotech', 'NYSE', TRUE),
                                                                                                 ('VUS', 'Virtus US Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('VDI', 'Virtus International Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('VWID', 'Virtus WMC International Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('BBP', 'Virtus Biotech ETF', 'ETF', 'US', 'USD', 'Biotech', 'NYSE', TRUE),
                                                                                                 ('VEMY', 'Virtus Stone Harbor Emerging Markets High Yield Bond ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('PCLO', 'Virtus Seix AAA Private Credit CLO ETF', 'ETF', 'US', 'USD', 'Fixed Income', 'NYSE', TRUE),
                                                                                                 ('VABS', 'Virtus Newfleet Securitized Income ETF', 'ETF', 'US', 'USD', 'Fixed Income', 'NYSE', TRUE),
                                                                                                 ('SDCP', 'Virtus Newfleet Short Duration Core Plus Bond ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('SEIX', 'Virtus Seix Senior Loan ETF', 'ETF', 'US', 'USD', 'Loan', 'NYSE', TRUE),
                                                                                                 ('VSHY', 'Virtus Newfleet Short Duration High Yield Bond ETF', 'ETF', 'US', 'USD', 'High Yield', 'NYSE', TRUE),
                                                                                                 ('VEM', 'Virtus Emerging Markets Dividend ETF', 'ETF', 'US', 'USD', 'Dividend', 'NYSE', TRUE),
                                                                                                 ('NFLT', 'Virtus Newfleet Multi-Sector Bond ETF', 'ETF', 'US', 'USD', 'Multi-Sector', 'NYSE', TRUE),
                                                                                                 ('UTES', 'Virtus Reaves Utilities ETF', 'ETF', 'US', 'USD', 'Utilities', 'NYSE', TRUE),
                                                                                                 ('KMID', 'Virtus KAR Mid-Cap ETF', 'ETF', 'US', 'USD', 'Mid Cap', 'NYSE', TRUE),
                                                                                                 ('PFFR', 'InfraCap REIT Preferred ETF', 'ETF', 'US', 'USD', 'REIT', 'NYSE', TRUE),
                                                                                                 ('PFFA', 'Virtus InfraCap US Preferred Stock ETF', 'ETF', 'US', 'USD', 'Preferred', 'NYSE', TRUE),
                                                                                                 ('JOET', 'Virtus Terranova US Quality Momentum ETF', 'ETF', 'US', 'USD', 'Momentum', 'NYSE', TRUE),
                                                                                                 ('VGRO', 'Virtus Silvant Growth Opportunities ETF', 'ETF', 'US', 'USD', 'Growth', 'NYSE', TRUE),
                                                                                                 ('VPC', 'Virtus Private Credit Strategy ETF', 'ETF', 'US', 'USD', 'Private Credit', 'NYSE', TRUE),
                                                                                                 ('AOA', 'iShares Core Aggressive Allocation ETF', 'ETF', 'US', 'USD', 'Asset Allocation', 'NYSE', TRUE),
                                                                                                 ('AOR', 'iShares Core Growth Allocation ETF', 'ETF', 'US', 'USD', 'Asset Allocation', 'NYSE', TRUE),
                                                                                                 ('AOM', 'iShares Core Moderate Allocation ETF', 'ETF', 'US', 'USD', 'Asset Allocation', 'NYSE', TRUE),
                                                                                                 ('AOK', 'iShares Core Conservative Allocation ETF', 'ETF', 'US', 'USD', 'Asset Allocation', 'NYSE', TRUE),
                                                                                                 ('BND', 'Vanguard Total Bond Market ETF', 'ETF', 'US', 'USD', 'Bond', 'NYSE', TRUE),
                                                                                                 ('BNDX', 'Vanguard Total International Bond ETF', 'ETF', 'US', 'USD', 'International Bond', 'NYSE', TRUE),
                                                                                                 ('VT', 'Vanguard Total World Stock ETF', 'ETF', 'US', 'USD', 'Global Equity', 'NYSE', TRUE),
                                                                                                 ('VTI', 'Vanguard Total Stock Market ETF', 'ETF', 'US', 'USD', 'Total Market', 'NYSE', TRUE),
                                                                                                 ('VXUS', 'Vanguard Total International Stock ETF', 'ETF', 'US', 'USD', 'International', 'NYSE', TRUE),
                                                                                                 ('TLT', 'iShares 20+ Year Treasury Bond ETF', 'ETF', 'US', 'USD', 'Long Bond', 'NASDAQ', TRUE),
                                                                                                 ('IEF', 'iShares 7-10 Year Treasury Bond ETF', 'ETF', 'US', 'USD', 'Intermediate Bond', 'NASDAQ', TRUE),
                                                                                                 ('HYG', 'iShares iBoxx High Yield Corporate Bond ETF', 'ETF', 'US', 'USD', 'High Yield', 'NYSE', TRUE),
                                                                                                 ('JNK', 'SPDR Bloomberg High Yield Bond ETF', 'ETF', 'US', 'USD', 'High Yield', 'NYSE', TRUE),
                                                                                                 ('EMB', 'iShares JPMorgan USD Emerging Markets Bond ETF', 'ETF', 'US', 'USD', 'Emerging Bond', 'NASDAQ', TRUE),
                                                                                                 ('EFA', 'iShares MSCI EAFE ETF', 'ETF', 'US', 'USD', 'Developed Intl', 'NYSE', TRUE),
                                                                                                 ('EEM', 'iShares MSCI Emerging Markets ETF', 'ETF', 'US', 'USD', 'Emerging Markets', 'NYSE', TRUE),
                                                                                                 ('IJH', 'iShares Core S&P Mid-Cap ETF', 'ETF', 'US', 'USD', 'Mid Cap', 'NYSE', TRUE),
                                                                                                 ('IJR', 'iShares Core S&P Small-Cap ETF', 'ETF', 'US', 'USD', 'Small Cap', 'NYSE', TRUE),
                                                                                                 ('IWM', 'iShares Russell 2000 ETF', 'ETF', 'US', 'USD', 'Small Cap', 'NYSE', TRUE),
                                                                                                 ('MDY', 'SPDR S&P MidCap 400 ETF Trust', 'ETF', 'US', 'USD', 'Mid Cap', 'NYSE', TRUE),
                                                                                                 ('VB', 'Vanguard Small-Cap ETF', 'ETF', 'US', 'USD', 'Small Cap', 'NYSE', TRUE),
                                                                                                 ('VO', 'Vanguard Mid-Cap ETF', 'ETF', 'US', 'USD', 'Mid Cap', 'NYSE', TRUE),
                                                                                                 ('XLK', 'Technology Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Technology', 'NYSE', TRUE),
                                                                                                 ('XLF', 'Financial Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Financial', 'NYSE', TRUE),
                                                                                                 ('XLV', 'Health Care Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Healthcare', 'NYSE', TRUE),
                                                                                                 ('XLI', 'Industrial Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Industrial', 'NYSE', TRUE),
                                                                                                 ('XLY', 'Consumer Discretionary Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Consumer', 'NYSE', TRUE),
                                                                                                 ('XLP', 'Consumer Staples Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Consumer Staples', 'NYSE', TRUE),
                                                                                                 ('XLE', 'Energy Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Energy', 'NYSE', TRUE),
                                                                                                 ('XLU', 'Utilities Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Utilities', 'NYSE', TRUE),
                                                                                                 ('XLRE', 'Real Estate Select Sector SPDR Fund', 'ETF', 'US', 'USD', 'Real Estate', 'NYSE', TRUE),
                                                                                                 ('IBB', 'iShares Biotechnology ETF', 'ETF', 'US', 'USD', 'Biotech', 'NASDAQ', TRUE),
                                                                                                 ('XBI', 'SPDR S&P Biotech ETF', 'ETF', 'US', 'USD', 'Biotech', 'NYSE', TRUE),
                                                                                                 ('SMH', 'VanEck Semiconductor ETF', 'ETF', 'US', 'USD', 'Semiconductors', 'NASDAQ', TRUE);

-- -----------------------------------------------------
-- 3. 期货 (Futures) - 100个 (中国四大期货交易所)
-- -----------------------------------------------------
INSERT INTO assets (symbol, name, asset_type, market, currency, sector, exchange, is_active) VALUES
-- 上海期货交易所 (SHFE)
('CU', '铜期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('AL', '铝期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('ZN', '锌期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('PB', '铅期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('NI', '镍期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('SN', '锡期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('AU', '黄金期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('AG', '白银期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('RB', '螺纹钢期货', 'FUTURES', 'CN', 'CNY', 'Steel', 'SHFE', TRUE),
('HC', '热轧卷板期货', 'FUTURES', 'CN', 'CNY', 'Steel', 'SHFE', TRUE),
('WR', '线材期货', 'FUTURES', 'CN', 'CNY', 'Steel', 'SHFE', TRUE),
('SS', '不锈钢期货', 'FUTURES', 'CN', 'CNY', 'Steel', 'SHFE', TRUE),
('RU', '天然橡胶期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'SHFE', TRUE),
('BU', '石油沥青期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'SHFE', TRUE),
('FU', '燃料油期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'SHFE', TRUE),
('SP', '纸浆期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'SHFE', TRUE),
('AO', '氧化铝期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('BR', '丁二烯橡胶期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'SHFE', TRUE),
('AD', '铸造铝合金期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('OP', '胶版印刷纸期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'SHFE', TRUE),
-- 大连商品交易所 (DCE)
('A', '黄大豆1号期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('B', '黄大豆2号期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('M', '豆粕期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('Y', '豆油期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('C', '玉米期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('CS', '玉米淀粉期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('P', '棕榈油期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('L', '聚乙烯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('V', '聚氯乙烯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('PP', '聚丙烯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('EB', '苯乙烯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('EG', '乙二醇期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('PG', '液化石油气期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'DCE', TRUE),
('BZ', '纯苯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'DCE', TRUE),
('J', '冶金焦炭期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'DCE', TRUE),
('JM', '焦煤期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'DCE', TRUE),
('I', '铁矿石期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'DCE', TRUE),
('JD', '鲜鸡蛋期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('LH', '生猪期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('LG', '原木期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('RR', '粳米期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('FB', '纤维板期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('BB', '胶合板期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
-- 郑州商品交易所 (CZCE)
('SR', '白糖期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('CF', '棉花期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('CY', '棉纱期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('OI', '菜籽油期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('RM', '菜籽粕期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('RS', '油菜籽期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('TA', 'PTA期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('MA', '甲醇期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('FG', '玻璃期货', 'FUTURES', 'CN', 'CNY', 'Materials', 'CZCE', TRUE),
('SA', '纯碱期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('UR', '尿素期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('PF', '短纤期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('PX', '对二甲苯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('PR', '瓶片期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('PL', '丙烯期货', 'FUTURES', 'CN', 'CNY', 'Chemicals', 'CZCE', TRUE),
('AP', '苹果期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('CJ', '红枣期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('PK', '花生仁期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('SF', '硅铁期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'CZCE', TRUE),
('SM', '锰硅期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'CZCE', TRUE),
('PM', '普通小麦期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('WH', '强麦期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('RI', '早籼稻期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('JR', '粳稻期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('LR', '晚籼稻期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
-- 中国金融期货交易所 (CFFEX)
('IF', '沪深300股指期货', 'FUTURES', 'CN', 'CNY', 'Index', 'CFFEX', TRUE),
('IH', '上证50股指期货', 'FUTURES', 'CN', 'CNY', 'Index', 'CFFEX', TRUE),
('IC', '中证500股指期货', 'FUTURES', 'CN', 'CNY', 'Index', 'CFFEX', TRUE),
('IM', '中证1000股指期货', 'FUTURES', 'CN', 'CNY', 'Index', 'CFFEX', TRUE),
('TS', '2年期国债期货', 'FUTURES', 'CN', 'CNY', 'Bond', 'CFFEX', TRUE),
('TF', '5年期国债期货', 'FUTURES', 'CN', 'CNY', 'Bond', 'CFFEX', TRUE),
('T', '10年期国债期货', 'FUTURES', 'CN', 'CNY', 'Bond', 'CFFEX', TRUE),
('TL', '30年期国债期货', 'FUTURES', 'CN', 'CNY', 'Bond', 'CFFEX', TRUE),
-- 上海国际能源交易中心 (INE)
('SC', '原油期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'INE', TRUE),
('NR', '20号胶期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'INE', TRUE),
('LU', '低硫燃料油期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'INE', TRUE),
('BC', '国际铜期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'INE', TRUE),
('EC', '集运指数欧线期货', 'FUTURES', 'CN', 'CNY', 'Index', 'INE', TRUE),
-- 广州期货交易所 (GFEX)
('SI', '工业硅期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
('LC', '碳酸锂期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
('PS', '多晶硅期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
('PD', '钯期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
('PT', '铂期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
-- 补充更多期货品种至100个
('CFG', '玉米期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('SOY', '大豆期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('WHT', '小麦期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('RICE', '稻谷期货', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('COT', '棉花期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('SUG', '白糖期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'CZCE', TRUE),
('OIL', '豆油期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('MEAL', '豆粕期货(远期)', 'FUTURES', 'CN', 'CNY', 'Agriculture', 'DCE', TRUE),
('STEEL', '钢材期货组合', 'FUTURES', 'CN', 'CNY', 'Steel', 'SHFE', TRUE),
('COAL', '动力煤期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'CZCE', TRUE),
('URAN', '铀期货', 'FUTURES', 'CN', 'CNY', 'Energy', 'INE', TRUE),
('LITH', '锂期货', 'FUTURES', 'CN', 'CNY', 'Metals', 'GFEX', TRUE),
('COPP', '铜期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('ALUM', '铝期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('ZINC', '锌期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('NICK', '镍期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('TIN', '锡期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('GOLD', '黄金期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('SILV', '白银期货(迷你)', 'FUTURES', 'CN', 'CNY', 'Metals', 'SHFE', TRUE),
('IRON', '铁矿石期货(远期)', 'FUTURES', 'CN', 'CNY', 'Metals', 'DCE', TRUE),
('COKE', '焦炭期货(远期)', 'FUTURES', 'CN', 'CNY', 'Energy', 'DCE', TRUE),
('COALG', '焦煤期货(远期)', 'FUTURES', 'CN', 'CNY', 'Energy', 'DCE', TRUE);

-- -----------------------------------------------------
-- 4. 加密货币 (Cryptocurrency) - 10个
-- -----------------------------------------------------
INSERT INTO assets (symbol, name, asset_type, market, currency, sector, exchange, is_active) VALUES
                                                                                                 ('BTC', 'Bitcoin', 'CRYPTO', 'Global', 'USD', 'Cryptocurrency', 'Coinbase', TRUE),
                                                                                                 ('ETH', 'Ethereum', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('SOL', 'Solana', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('BNB', 'Binance Coin', 'CRYPTO', 'Global', 'USD', 'Exchange Token', 'Binance', TRUE),
                                                                                                 ('ADA', 'Cardano', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('DOT', 'Polkadot', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('AVAX', 'Avalanche', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('LINK', 'Chainlink', 'CRYPTO', 'Global', 'USD', 'Oracle', 'Coinbase', TRUE),
                                                                                                 ('SUI', 'Sui Network', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE),
                                                                                                 ('NEAR', 'Near Protocol', 'CRYPTO', 'Global', 'USD', 'Smart Contract', 'Coinbase', TRUE);
